# Composition Correctness Metrics Configuration
# Production configuration for DreamLayer AI

yolo:
  model: "yolov8n.pt"
  conf_threshold: 0.25
  iou_threshold: 0.5
  max_detections: 100

matching:
  iou_threshold: 0.5
  count_tolerance: 1
  exact_counts: false

# HSV color ranges for color detection
colors:
  red: 
    - [0, 50, 50]
    - [10, 255, 255]
  orange:
    - [11, 50, 50] 
    - [25, 255, 255]
  yellow:
    - [26, 50, 50]
    - [35, 255, 255]
  green:
    - [36, 50, 50]
    - [85, 255, 255]
  cyan:
    - [86, 50, 50]
    - [99, 255, 255]
  blue:
    - [100, 50, 50]
    - [130, 255, 255]
  purple:
    - [131, 50, 50]
    - [160, 255, 255]
  brown:
    - [10, 50, 20]
    - [20, 255, 200]
  black:
    - [0, 0, 0]
    - [180, 255, 30]
  white:
    - [0, 0, 200]
    - [180, 30, 255]
  gray:
    - [0, 0, 50]
    - [180, 30, 200]

# Synonym mappings to COCO classes
synonyms:
  dog: ["canine", "puppy", "hound", "pup", "doggy"]
  cat: ["feline", "kitten", "kitty", "pussy"]
  car: ["vehicle", "automobile", "auto", "sedan", "suv"]
  person: ["human", "man", "woman", "people", "individual", "guy", "girl"]
  bird: ["eagle", "hawk", "owl", "robin", "sparrow", "pigeon"]
  house: ["home", "building", "residence", "mansion"]
  tree: ["oak", "pine", "maple", "birch", "willow"]
  flower: ["rose", "tulip", "daisy", "sunflower", "lily"]
  bottle: ["container", "flask", "jar"]
  chair: ["seat", "stool", "armchair"]
  book: ["novel", "magazine", "publication"]
  laptop: ["computer", "notebook", "pc"]
  phone: ["smartphone", "mobile", "cellphone"]
  
# COCO class mappings (subset of most common classes)
coco_classes:
  - "person"
  - "bicycle" 
  - "car"
  - "motorcycle"
  - "airplane"
  - "bus"
  - "train"
  - "truck"
  - "boat"
  - "bird"
  - "cat"
  - "dog"
  - "horse"
  - "sheep"
  - "cow"
  - "elephant"
  - "bear"
  - "zebra"
  - "giraffe"
  - "backpack"
  - "umbrella"
  - "handbag"
  - "tie"
  - "suitcase"
  - "bottle"
  - "wine glass"
  - "cup"
  - "fork"
  - "knife"
  - "spoon"
  - "bowl"
  - "banana"
  - "apple"
  - "sandwich"
  - "orange"
  - "broccoli"
  - "carrot"
  - "pizza"
  - "donut"
  - "cake"
  - "chair"
  - "couch"
  - "potted plant"
  - "bed"
  - "dining table"
  - "toilet"
  - "tv"
  - "laptop"
  - "mouse"
  - "remote"
  - "keyboard"
  - "cell phone"
  - "microwave"
  - "oven"
  - "toaster"
  - "sink"
  - "refrigerator"
  - "book"
  - "clock"
  - "vase"
  - "scissors"
  - "teddy bear"
